"""initial_schema_step07

Revision ID: 03906fa596ea
Revises: 
Create Date: 2026-09-25 19:59:33.200296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03906fa596ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price_normal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_peak', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_offpeak', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('peak_start', sa.String(length=5), nullable=False),
    sa.Column('peak_end', sa.String(length=5), nullable=False),
    sa.Column('peak_start_2', sa.String(length=5), nullable=False),
    sa.Column('peak_end_2', sa.String(length=5), nullable=False),
    sa.Column('offpeak_start', sa.String(length=5), nullable=False),
    sa.Column('offpeak_end', sa.String(length=5), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('price_normal >= 0', name='ck_tariff_price_normal_positive'),
    sa.CheckConstraint('price_offpeak >= 0', name='ck_tariff_price_offpeak_positive'),
    sa.CheckConstraint('price_peak >= 0', name='ck_tariff_price_peak_positive'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariffs_id'), 'tariffs', ['id'], unique=False)
    op.create_index(op.f('ix_tariffs_station_id'), 'tariffs', ['station_id'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reference_id', sa.String(length=50), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("transaction_type IN ('TOPUP', 'CHARGE_FEE', 'REFUND')", name='ck_wallet_transaction_type_valid'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_id'), 'wallet_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_wallet_id'), 'wallet_transactions', ['wallet_id'], unique=False)
    op.create_table('charging_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=False),
    sa.Column('tariff_id', sa.Integer(), nullable=False),
    sa.Column('applied_price_per_kwh', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meter_start_kwh', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('meter_stop_kwh', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_kwh', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stop_reason', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'COMPLETED', 'FAILED', 'CANCELLED')", name='ck_session_status_valid'),
    sa.CheckConstraint('total_amount >= 0', name='ck_session_total_amount_non_negative'),
    sa.CheckConstraint('total_kwh >= 0', name='ck_session_total_kwh_non_negative'),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charging_sessions_connector_id'), 'charging_sessions', ['connector_id'], unique=False)
    op.create_index(op.f('ix_charging_sessions_id'), 'charging_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_charging_sessions_tariff_id'), 'charging_sessions', ['tariff_id'], unique=False)
    op.create_index(op.f('ix_charging_sessions_user_id'), 'charging_sessions', ['user_id'], unique=False)
    op.add_column('wallets', sa.Column('is_debt_locked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'is_debt_locked')
    op.drop_index(op.f('ix_charging_sessions_user_id'), table_name='charging_sessions')
    op.drop_index(op.f('ix_charging_sessions_tariff_id'), table_name='charging_sessions')
    op.drop_index(op.f('ix_charging_sessions_id'), table_name='charging_sessions')
    op.drop_index(op.f('ix_charging_sessions_connector_id'), table_name='charging_sessions')
    op.drop_table('charging_sessions')
    op.drop_index(op.f('ix_wallet_transactions_wallet_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_tariffs_station_id'), table_name='tariffs')
    op.drop_index(op.f('ix_tariffs_id'), table_name='tariffs')
    op.drop_table('tariffs')
    # ### end Alembic commands ###
