"""add last seen at to charging points

Revision ID: 5ba0e05433d7
Revises: 45ab6640633a
Create Date: 2026-10-03 14:34:20.055181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ba0e05433d7'
down_revision: Union[str, None] = '45ab6640633a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charging_points', sa.Column('charge_point_vendor', sa.String(length=100), nullable=True))
    op.add_column('charging_points', sa.Column('charge_point_model_name', sa.String(length=100), nullable=True))
    op.add_column('charging_points', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charging_points', 'last_seen_at')
    op.drop_column('charging_points', 'charge_point_model_name')
    op.drop_column('charging_points', 'charge_point_vendor')
    # ### end Alembic commands ###
