"""add_checkpoint_and_soc_to_sessions

Revision ID: f99adeda980d
Revises: 03906fa596ea
Create Date: 2026-09-25 20:24:47.730601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f99adeda980d'
down_revision: Union[str, None] = '03906fa596ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charging_sessions', sa.Column('current_soc', sa.Float(), nullable=False))
    op.add_column('charging_sessions', sa.Column('last_checkpoint_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('wallets', sa.Column('is_debt_locked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'is_debt_locked')
    op.drop_column('charging_sessions', 'last_checkpoint_at')
    op.drop_column('charging_sessions', 'current_soc')
    # ### end Alembic commands ###
