"""add_charge_points_and_connectors

Revision ID: 98fa4a593c79
Revises: 45fd43d6126c
Create Date: 2026-09-23 12:19:51.843178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98fa4a593c79'
down_revision: Union[str, Sequence[str], None] = '45fd43d6126c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charge_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charge_points_code'), 'charge_points', ['code'], unique=True)
    op.create_index(op.f('ix_charge_points_station_id'), 'charge_points', ['station_id'], unique=False)
    op.create_table('connectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charge_point_id', sa.Integer(), nullable=False),
    sa.Column('connector_number', sa.Integer(), nullable=False),
    sa.Column('connector_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['charge_point_id'], ['charge_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('charge_point_id', 'connector_number', name='uix_connector_charge_point_number')
    )
    op.create_index(op.f('ix_connectors_charge_point_id'), 'connectors', ['charge_point_id'], unique=False)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.drop_index(op.f('ix_connectors_charge_point_id'), table_name='connectors')
    op.drop_table('connectors')
    op.drop_index(op.f('ix_charge_points_station_id'), table_name='charge_points')
    op.drop_index(op.f('ix_charge_points_code'), table_name='charge_points')
    op.drop_table('charge_points')
    op.drop_table('stations')
    # ### end Alembic commands ###
